// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZC9GeuQglYu8eeMCr_t0l4U7sOOJo2BE',
    appId: '1:849884032639:web:1d5e2d4eecd723eb94194a',
    messagingSenderId: '849884032639',
    projectId: 'bayflow-3e482',
    authDomain: 'bayflow-3e482.firebaseapp.com',
    storageBucket: 'bayflow-3e482.firebasestorage.app',
    measurementId: 'G-F782SQW85C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28gpaxymbJiy9DOsfGqlysH1dSHF7joo',
    appId: '1:849884032639:android:f915dbf54bb4b96994194a',
    messagingSenderId: '849884032639',
    projectId: 'bayflow-3e482',
    storageBucket: 'bayflow-3e482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS1UgKqoMydhcvsVpfKRoQBtPXf4hI_fA',
    appId: '1:849884032639:ios:7a633aa1d49a5d4994194a',
    messagingSenderId: '849884032639',
    projectId: 'bayflow-3e482',
    storageBucket: 'bayflow-3e482.firebasestorage.app',
    iosBundleId: 'com.example.bayFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS1UgKqoMydhcvsVpfKRoQBtPXf4hI_fA',
    appId: '1:849884032639:ios:7a633aa1d49a5d4994194a',
    messagingSenderId: '849884032639',
    projectId: 'bayflow-3e482',
    storageBucket: 'bayflow-3e482.firebasestorage.app',
    iosBundleId: 'com.example.bayFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZC9GeuQglYu8eeMCr_t0l4U7sOOJo2BE',
    appId: '1:849884032639:web:f1dd9ef07070aafc94194a',
    messagingSenderId: '849884032639',
    projectId: 'bayflow-3e482',
    authDomain: 'bayflow-3e482.firebaseapp.com',
    storageBucket: 'bayflow-3e482.firebasestorage.app',
    measurementId: 'G-SFH7MDY2K1',
  );
}
